# Generated by Django 5.2.17 on 2026-09-05 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kinetiq_routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSessionRecord',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=24)),
                ('configuration', models.JSONField()),
                ('confirmed_repetitions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinetiq_routines.routinerecord')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=160)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kinetiq_workouts.workoutsessionrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='workoutsessionrecord',
            index=models.Index(fields=['owner', '-updated_at'], name='session_owner_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyreceipt',
            constraint=models.UniqueConstraint(fields=('owner', 'operation', 'key'), name='idempotency_owner_operation_key_unique'),
        ),
    ]
