# Generated by Django 5.2.17 on 2026-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetiq_workouts', '0003_performed_activity_and_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionrecord',
            name='vision_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsessionrecord',
            name='vision_lease_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='workoutsessionrecord',
            name='vision_poll_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsessionrecord',
            name='vision_poll_lease_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
