# Generated by Django 5.2.17 on 2026-09-22 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetiq_workouts', '0004_vision_lease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionObservationQuarantineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_id', models.CharField(max_length=120)),
                ('observed_session_id', models.CharField(max_length=120)),
                ('observed_target_person_id', models.CharField(max_length=120)),
                ('expected_session_id', models.CharField(max_length=120)),
                ('expected_target_person_id', models.CharField(blank=True, max_length=120, null=True)),
                ('epoch', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_observation_quarantines', to='kinetiq_workouts.workoutsessionrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['session', '-detected_at'], name='vision_quarantine_session_idx')],
            },
        ),
    ]
