# Generated by Django 5.2.17 on 2026-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetiq_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetemplaterecord',
            name='supported_experience_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='routinetemplaterecord',
            name='supported_limitation_adaptations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='routinetemplaterecord',
            name='supported_workout_spaces',
            field=models.JSONField(default=list),
        ),
    ]
