# Generated by Django 5.2.17 on 2026-09-15 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRevisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_id', models.UUIDField(db_index=True)),
                ('revision', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('measure', models.CharField(blank=True, max_length=80, null=True)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals_goal_revisions',
                'indexes': [models.Index(fields=['owner', '-revision'], name='goal_owner_rev_idx'), models.Index(fields=['owner', '-created_at'], name='goal_owner_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'goal_id', 'revision'), name='goal_owner_id_revision_unique')],
            },
        ),
    ]
