# Generated by Django 5.2.17 on 2026-09-15 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kinetiq_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileRecord',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('experience_level', models.CharField(default='RETURNING', max_length=32)),
                ('availability_days_per_week', models.PositiveSmallIntegerField(default=3)),
                ('target_session_minutes', models.PositiveSmallIntegerField(default=15)),
                ('available_equipment', models.JSONField(default=list)),
                ('workout_space', models.CharField(default='LIVING_ROOM', max_length=64)),
                ('preferences', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('limitations', models.JSONField(default=list)),
                ('coaching_tone', models.CharField(default='CALM', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles_user_profile',
            },
        ),
    ]
