# Generated by Django 5.2.17 on 2026-09-21 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhotoRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('s3_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_length', models.PositiveIntegerField()),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_progress_photos',
            },
        ),
        migrations.CreateModel(
            name='MediaUploadReceiptRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinetiq_media.progressphotorecord')),
            ],
            options={
                'db_table': 'media_upload_receipts',
            },
        ),
        migrations.AddIndex(
            model_name='progressphotorecord',
            index=models.Index(fields=['owner', '-created_at'], name='media_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphotorecord',
            index=models.Index(fields=['owner', 'session_id'], name='media_owner_session_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphotorecord',
            index=models.Index(fields=['owner', 'status'], name='media_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediauploadreceiptrecord',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='media_owner_idempotency_unique'),
        ),
    ]
