# Generated by Django 5.2.17 on 2026-09-22 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetiq_media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCleanupJobRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("photo_id", models.UUIDField(db_index=True)),
                ("s3_key", models.CharField(max_length=512)),
                ("reason", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "media_cleanup_jobs",
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="media_cleanup_due_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("photo_id", "reason"),
                        name="media_cleanup_one_pending_per_photo_reason",
                    )
                ],
            },
        ),
    ]
