# Generated by Django 5.2.17 on 2026-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetiq_media", "0002_mediacleanupjobrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediacleanupjobrecord",
            name="verify_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressphotorecord",
            name="upload_authorized_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
