# Generated by Django 5.2.17 on 2026-09-22 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetiq_media", "0003_mediacleanupjobrecord_verify_after_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaEventOutboxRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("photo_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(default="ProgressPhotoDeleted.v1", max_length=60)),
                ("status", models.CharField(max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "media_event_outbox",
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="media_event_due_idx")
                ],
            },
        ),
    ]
