# Generated by Django 5.2.17 on 2026-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kinetiq_media", "0005_decouple_cleanup_and_outbox_owner_from_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressphotorecord",
            name="final_s3_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
